# Elements of transport protocol

## Addressing

Le porte sono indirizzi di transport layer ai quali i processi si mettono in ascolto per richieste di connessioni. TSAP (Transport Service Access Point) é un endpoint specifico del transport layer. NSAP é un endpoint del network layer; IP sono NSAP. Ogni computer ha un solo NSAP e ad un NSAP possono corrispondere piú TSAP.
Portmapper é un processo speciale che associa al nome del servizio un endpoint TSAP, dopo di che il servizio utente rilascia la connessione con il portmapper e stabilisce una con il servizio desiderato.
Initial Connectin Protocol: ogni macchina che fornisce servizi (poco utilizzati), utilizza un process server che agisce da proxy. Tutti i client che desiderano usufruire dei servizi di una macchina comunicano con questo process server che mette in comunicazione con i servizi. Il process server controlla e risponde di tutti gli indirizzi TSAP. Questo metodo é utilizzabile solo per server creati su richiesta.

## Connection Estabilishment

Un protocollo deve essere costruito per essere corretto in tutte le curcostanze; soltanto il caso comune deve essere implementato in modo efficiente per ottenere buone performance. Ma il protocollo deve affrontare tutte le evenienze senza che si rompi.
Non si puó prevenire che i pacchetti vengano duplicati o ritardati, ma, quando succede, i pacchetti devono essere rifiutati.
Il problema puó essere affrontato in piú modi, nessuno dei quali totalmente soddisfacente:
1) Indirizzi usa e getta: ogni volta che é necessario un TSAP, esso viene generato. Quando un connessione viene rilasciata, l’indirizzo viene eliminato e mai piú utilizzato.
2) Identificatori univoci per ogni connessione scelto dalla entitá che inizia e messa in ogni segmento, incluso nella richiesta di connessione. Dopo che la connessione é stata rilasciata, il transport entity aggiorna la tabella delle connessioni come obsoleta. Il problema é mantenere una tabella capace di contenere tutte le coppie identificatore-PeerTransportEntity, persente in sia lato server che client. In caso di perdita della tabella la connessione non é piú utilizzabile.
3) Tempo massimo di vita di un pacchetto. Quest’ultimo metodo é il piú gestibile. Viene sviluppato in seguito in base alle diverse metodolofie:
a) Prevenire che i pacchetti ciclino combinato con qualche metodo per contenere i ritardi.
b) hop counter decrementato ogni volta che il pacchetto viene inoltrato.
3) timestamp della creazione del pacchetto. Necessita la sincrinizzazione dei router.
Bisogna anche assicurarsi che eventuali acknowledgment diano morti, i quali avranno tempo di vita kT, dove T é il tempo di vita del pacchetto corrispondente e k una costante arbitraria.
Il metodo utilizzato, ad esempio in TCP, consiste nel utilizzare sequence number che non verranno riutilizzati prima di T secondi. Il periodo T e la frequenza di pacchetti al secondo determinano la lunghezza del sequence number. Puó capitare che un duplicato venga consegnato con successo entro il tempo di validitá T.
Per quanto riguarda il problema della perdita della memoria dopo un crash, una soluzione puó essere di mantenere ad idle il transport entity per T secondi dopo un ripristino.

É stato proposto di utilizzare un orologio (il quale non deve essere sincoronizzato) da parte degli host. Ogni sequence number viene computato in base all’orologio e ogni nuova connessione deve aspettare che venga generato un nuovo sequence number prima di poter essere stabilita.

Ogni qual volta un host riceve un segmento, chiede la conferma all’altro host. Se quest’ultimo stava effettivamente cercando di cominicare, allora risponderá con un ACK, altrimenti nega la richiesta.
Unico problema che rende possibile attacchi poiché l’utilizzo del tempo rende piú predicibile il sequence number.

## Connection Release

Asimmetrico: come nel sistema telefonico, quando uno dei due rilascia la connessione, quest’ultima é interrotta. Puó produrre perdita di dati se viene interrotta prima che l’altro finisca di inviare.
Simmetrico: la connessione viene interrotta solo quando entrambi rilasciano. Un componenete continua a ricevere anche se ha inviato una richiesta di disconnessione.

Le parti possono eseguono un massimo di N tentativi di trasmissione, e lo stesso vale in caso di ricezione di una risposta. In quest’ultimo caso, se non si ricevono piú segmenti per un tempo T prestabilito, la connessione viene rilasciata automaticamente.

## Error Control and Flow Control

Error Control: si sddicura che i dari vengono consegnati con il desigderio di affidabilitá (solitamente si vuole senza errori).
Flow Control: non saturare gli slow transmitter.
Riporto alcuni meccanismi giá incontrati nel data link layer che vengono utilizzati anche nel transport layer:
1) un frame porta un codice error-detecting (CRC o checksum).
2) un frame porta un sequence number per identificare se stesso ed é ritrasmesso fin quando il ricevente non risponde con ACK (ARQ = Automatic Repeat reQuest).
3) protocollo stop-and-wait per limitare i fast senders e non saturare un ricevente.
4) sliding windows protocol (anche per trasporto bidirezionale).
Il trasnport layer implementa a sua volta un checksum, nonostante sia giá presente nel data likn layer poiché quest’ultimo serve per il trasporto di un singolo collegamento (protegge la trasmissione tra una linea di trasmissione). Mentre, il checksum del transport layer, é utilizzato per la protezione dei segmenti fino al destinatario (end-to-end) per l’intero network. Infatti puó capitare che i frame vengano corrotti all’interno di un router, cosicché la trasmissione non generi errori e il messaggio recapitato scorretto. Il checksum del data link layer non é necessario, ma migliora le performance in quanto evita ritrasmissioni in caso di errori.
La grandezza delle sliding windows dipende dal tipo di linea di trasmissione, ad esempio il protocollo 802.11 (wifi) utilizza finestre piccole, poiché la perdita di messaggi é probabile e necessita di meccanismi si ACK. Altri portocolli piú affidabili (come cavo e fibre) la ritrasmissione non é contemplata nel data link layer, poiché gli errori sono poco frequenti.
Dato che i transport protocol eutilizzano grandi finestre e gli host possono avere molte connessioni, ciascune delle quali trattata separatamente, é necessario abbastanza buffer per contenere le slinding windows. I buffer sono sia lato mittente che destinatario (per ACK e ritrasmissione). Se é disponibile abbastanza spazio nel buffer il segmento in entrata é mantenuto, altrimenti viene scartato; il mittente é pronto a ritrasmettere e c’é solo spreco di risorse, poiché continua a inoltrare fin quando non riceve un ACK. C’é quindi il problema di che dimensione devono essere gli slot dei buffer (fissa, variabile, buffer circolare o su richiesta).

Per prevenire casi di deadlock, tutti i gli host dovrebbero mandare segmenti di controllo contente ACK e informazioni sul buffer.

## Crash Recovery

Quando un host crasha e viene ripristinato, non sa piú il punto a cui era rimasto. Gli host a cui era connesso possono essere in attesa di segmenti (la connessione si é interrotta prima che finisse la trasmissione) e viene chiamato stato S1, altrimenti S0 (non attende nessun segmento). In questo caso il client deve decidere se ritrasmettere il segmento piú recente.
Ci sono sempre situazioni in cui il protocollo fallisce nel ripristino. Il server puó fare o ACK first o write first. Il client puó agire in quattro modi: sempre ritrasmettere, mai ritrasmettere, retransmit solo in caso di stato S0 e ritrasmettere solo in caso di stato S1. Ogni combinazione di queste strategie porta a casi indesiderati, riportati in figura. Conclusione: nessun crash e recovery di un host puó essere resto trasparente ai layer superiori, nemmeno con protocolli piú elaborati.

# Congestion Control

Il controllo e la prevenzione delle congestioni é compito del lavoro del network layer e transport layer. La congestione accade a livello dei router e viene rilevata a livello di network layer. L’unico modo per evitare congestioni é controllare il throughput di un host e quindi transport layer.

## Desiderable Bandwidth Allocation

Una buona allocazione di banda deve essere tale da saturare quella disponibile ma non incappare in congestione, non competere per con altri transport entity e adattarsi velocemente alle richieste.

### Efficiency and Power

Goodput = quantitá di pacchetti utili arrivati al destinatario.
Power = load/delay

### Min-Max Fairness
Spesso ogni le reti non hanno banda riservata per ogni flusso o connessione. Molte connessioni sfrutteranno tutta la banda disponibile o concentrati insime sotto la stessa allocazione.
Compromesso tra fairness e efficienza. Differenti connessioni avranno percorsi differenti con bande differenti.
Quando si utilizza Max-Min fairness, la banda di ogni connessione inizia da zero e aumenta lentamente fino a quando non raggiunge il collo di bottiglia, che sia la banda massima dell’host o di un link del percorso.
Importante é che ogni connesione non vada in starvation.

### Convergence

Un buon algortmo di controllo dovrebbe convergere rapidamente al suo punto ottimale e ricalcolarlo in caso di variazione del punto di ottimo.

## Regulating the Sending Rate

Il metodo con il quale il transport layer regola la frequenza di inoltro dipende anche dal metodo di feedback che riceve dal network. Reti diverse utilizzano feedback diversi. I feedback possono essere impliciti o espicliti. Per esplicito si intende, per esempio, se il network comunica al destinatario la velocitá precisa al quale inoltrare, oppure se comunica l’avvenuta congestione e di rallentrare ma non percisa quanto. La quantitá di incremento o decremento é data dalla legge di controllo.

Un buon algoritmo utilizzato é Additive Increase Multiplicative Decrease (AIMD) che garantisce una legge di controllo appropriata, fair ed efficiente.

## Wireless Issues

In teoria il controllo delle congestioni dovrebbe essere indipendente dal network e dal datalink layer, ma in pratica le connessioni wireless negano questa buona pratica. Molti meccanismi di feedback utilizzano come sengale il packet loss, ma le connessioni wireless hanno di base una alto livello di packet loss ben oltre il il segnale di congestione utilizzato per il  caso wired. Cosí i normali metodi di rilevamento di congestione, utilizzati per gli altri metodi di comunicazione, limiterebbero fortemente le connessioni wireless.
La cosa migliore sarebbe che questi metodi di rilevamento sappiano distunguere da perdita di pacchetti dovuto al metodo di trasmissione e perdita per banda insufficiente; ció non é possibile. Una soluzione puó essere mascherare la perdita di pacchetti dovuta alla trasmissione, con la ritrasmissione dei pacchetti (ad esempio 802.11 utilizza il protocollo stop-and-wait  e ritrasmettendo piú volte se é avvunuta la perdita del pacchetto).
Internet comprende percorsi eterogenei e non c’é modo per comunicare quali link comprendono quel percorso. Inoltre una perdita di pacchetti dovrebbe causare solo un meccanismod, poiché é dovuto o a trasmission error o congestione.
La soluzione quindi é utilizzare lo stesso meccanismo ma con timescale diversi. La ristasmissione si compie nell’ordine di microsecondi a millisecondi, mentre la perdita avviene nell’ordine di millisecondi a secondi. Ció permette ai wireless link di rilevare perdita di pacchetti e ritrasmettere prima che venga rilevata congestione.

# UDP

Internet utilizza principalmente due protocolli, uno connectionless (UDP) e uno connection-oriented (TCP).
Il compito di UDP é quello di inviare pacchetti ad un process e basta, cosicché le applicazioni possano costruire i loro protocolli al di sopra di esso. Al contrario il TCP, fornisce molteplici artifici, aggiungendo affidabilitá con ritrasmissione, flow control per conto dell’applicazione.

UDP sta per User Datagram Protocol e fornisce un metodo per inoltrare pacchetti incapsulati in datagrammi IP senza dover stabilire connessioni.
L’UDP trasmette segmenti composti da un header di 8 byte seguito dal payload. Le due porte servono per identificare gli endpoint di destinazione e di mittente. Quando un segmento UDP viene consegnato, il payload viene consegnato al processo associato alla porta di destinazione. Di fatto, aggiunge soltanto le porte al pacchetto IP, senza le quali non si potrebbe sapere il processo destinatario.
Il campo UDP Lenght comprende sia l’header UDP che il payload, per cui la lunghezza minima é 8byte fino al massimo consentito dai pacchetti IP.
Il checksum é opzionale e verifica sia l’header, sia il payload, sia lo pseudo header IP.
UDP non compie flow control, congestion control o ritrasmissione; tutto ció é compito del user process. Offre solo la possibilitá di multiplexare un pacchetto IP a piú user process e end-to-end error detection.
Fornisce strumenti necessati, per alcune applicazioni, come packet flow, error control e timing.
Un caso per cui é molto utilizzato é l’invio di piccoli pacchetti, i quali , se non arrivano, vengono timeoutati e ritramessi dal user.
Non é necessario alcun setup o release.

# TCP


